<!-- col 12 -->
<br><br><br><br><br>
<div class="col-md-12 ">
<div class="col-lg-4 col-md-6 col-12 col-sm-6 shadow-lg mx-auto text-center my-4 card-body  fade show alert-danger alert-dismissible" role="alert">
<h3 class = "card-title alert-100 " >Cuenta desactivada</h3><br><br>
                <h5 class = "card-text">Usted ha registrado exitosamente sus datos, sin embargo requiere activación por parte del administrador o no ha iniciado sesion correctamente</h5><br><br>
              
            </div>
      <div class="col-md-3"></div>
   </div>
</div><br><br><br><br>