<?php
echo'<br><br><br><br><br>';
cardtitulo('Informe de Facturación');
?>


<div class="card card-body box-card text-center col-md-10 col-lg-6 col-12 mx-auto">
    <!--<div class="container">-->
    <div class=" container-fluid ">
        <div class="card card-body  shadow-lg">
            <form method="POST">
                <div class="row">
                    <div class="col-md-4">
                        <!-- derecha -->
                        <label for="start">Fecha inicial:</label>
                        <div class="form-group"><input class="form-control" type="date" id="start" name="f1" value="<?=( $_POST['f1']??'2015-01-01')?>" min="0000-00-00" max="9999-99-99"></div>
                    </div>
                    <div class="col-md-4">
                        <label for="start">Fecha fin:</label>
                        <div class="form-group"><input class="form-control" type="date" id="start" name="f2" value="<?= (  $_POST['f2']??date('Y-m-d')) ?>"></div>
                    </div>
                    <div class="col-md-4 ">
                        <!-- derecha -->
                        <label for="estatus">Estado de factura</label>
                        <select name="estatus" id="estatus" class="form-control" onchange="submit(this)">
<?php
foreach($this->estado as $i => $d){
    echo '<option  '.(( isset( $_POST['estatus']) && $i == $_POST['estatus'] )? ' selected ' : '').'  value="'.$i.'">'.$d.'</option>';
}
?>

                        </select>
                    </div><!-- fin primera columna de 6 -->
                </div><!-- fin primera columna de 6 -->
                <div class="row">
                    <div class="col-md-6 mx-auto">
                        <!-- derecha -->
                        <div class="form-group"> <input class="btn btn-primary form-control" type="submit" value="Ver informe" name="consulta"></div>
                    </div><!-- fin primera columna de 6 -->
                </div>
            </form>
        </div><!-- fin de segunda columna de 6 -->
    </div>
</div><!-- fin de row -->
<?php
if (isset($this->datos) && ($this->datos['response_status'] == 'ok')) {
?>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table id="example" class="table bg-white table-striped table-bordered" cellspacing="0" width="100%">
                        <thead class="bg-dark text-white text-center">
                            <tr>
                                <th> fecha</th>
                                <th> Nombre de cliente</th>
                                <th> Medio de pago</th>
                                <th> Iva</th>
                                <th> total</th>
                                <th> estado</th>
                                <th> Factura No.</th>
                            </tr>
                        </thead>
                        <tbody>
<?php
foreach ($this->datos['response_msg'] as $i => $d) {
?>
                                <tr>
                                    <td><?= $d[0] ?></td>
                                    <td><?= $d[1] . ' ' . $d[2] ?> </td>
                                    <td><?= $d[7] ?></td>
                                    <td><?= ('$' . number_format(($d[4]), 0, ',', '.'))  ?></td>

                                    <td><?= '$' . number_format($d[3], 0, ',', '.');  ?></td>
                                    <td><?= $this->estado [$d[5]] ?> </td>
                                    <td class="text-center mx-auto">
                                        <button href="" class="btn btn-circle btn-success btn" data-bs-toggle="tooltip" data-bs-placement="right" title="Consultar factura" type="submit" name="f" href="javascript:void(0)" onclick="PopupCenter('<?= BASE_URL . 'empleado/unifactura?f=' . $d[6] ?>','Amoblando-detalle','1000','1000');">
                                            <?= $d[6] ?> </i></i>
                                        </button>
                                        <input type="hidden" name="accion" value="consFactura">
                                    </td>
                                </tr>
                            <?php
                            }
                            ?>
                            <tr>
                            <td><strong>Total en letras</strong> </td>
                            <td colspan="3" ><?= $this->total['letras'] ?> </td>
                            <td colspan="2" ><strong>Total Numeros</strong></td>
                            <td><?=  '$' . number_format($this->total['numeros'] , 0, ',', '.');  ?>  </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>        
    </div>
    <div class="container-fluid">
    <div class="my-2">
        <div id="chart_div" style="width: 100%; height: 500px;"></div>
        </div>
    </div>

<?php
} else {

    if (isset($this->facturas)) {
        echo '<div class="alert text-center col-md-4 mx-auto alert-info alert-dismissible fade show" role="alert">
' . $this->facturas['response_msg'] . '      
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true"></span>
</button>
</div>';
    }
}
?>


<script>
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Valor Total', 'Valor total'],
<?php
if(isset($t)) foreach( $t as $i => $d ){
?>

          ['<?= $i ?>', <?= $d  ?> ],
<?php
}
?>
         // ['2014',  1170  ],
         // ['2015',  660   ],
         // ['2016',  1030  ]
        ]);

        var options = {
          title: 'Estadística de ventas',
          hAxis: {title: 'Valor total por fecha',  titleTextStyle: {color: '#333'}},
          vAxis: {minValue: 0}
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
</script>
