<?php
cardtitulo("Medida");
?>
<script>
   function eliminarMed(id_med) {
      var conf = confirm('Esta seguro de eliminar medida con id' + id_med + " ?");
      if (conf) {
         window.location = "<?= BASE_URL.'medida/' ?>?d=1&id=" + id_med;
      }
   }
</script>
<div class="container ">
   <div class="row">
      <div class=" col-sm-6 col-md-6 col-lg-6 mx-auto ">
         <?php
         if (isset($_SESSION['message'])) {  ?>
            <!-- alerta boostrap -->
            <div class="col-lg-8 alert alert-<?= $_SESSION['color']   ?> alert-dismissible fade show" role="alert">
               <?= $_SESSION['message']  ?>
               <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
               </button>
            </div>
         <?php
            setMessage();
         }
         ?>
         <br><br><br><br><br>
         <div class="container-fluid">
            <div class="card col-md-8 box-card">
               <div class="card-header shadow">Registro</div>
               <div class="card-body">
                  <form action="" method="POST">
                     <div class="form-group"><input class="form-control" type="text" name="nom_medida" placeholder="Medida" required autofocus maxlength="35"></div>
                     <div class="form-group"><input class="form-control" type="text" name="acron_medida" placeholder="Acrónimo" required autofocus maxlength="5"></div>
                     <input type="hidden" name="accion" value="insertMedida">
                     <div class="form-group"><input class="form-control btn btn-primary" type="submit" name="submit" value="Crear Medida"></div>
                  </form>
               </div><!-- fin card body -->
            </div><!-- fin de card -->
         </div>
      </div>
<?php
if ($this->datos['response_status'] == 'ok') {
?>
         <div class="col-sm-6 col-md-6 col-lg-6   mx-auto  p2 mt-3">
            <table id="example" class="bg-white box-card text-center col-lg-10 col-mg-10">
               <thead>
                  <tr>
                     <th> <i></i> ID_medida</th>
                     <th> <i></i> Medida</th>
                     <th> <i></i> Acrónimo</th>
                     <th> <i></i> Acción</th>
                  </tr>
               </thead>
               <tbody>
                  <?php
                  foreach ($this->datos['response_msg'] as $i => $row) {
                  ?>
                     <tr>
                        <td><?= $row['ID_medida'] ?></td>
                        <td><?= $row['nom_medida'] ?></td>
                        <td><?= $row['acron_medida'] ?></td>
                        <td>
                           <form action="<?= BASE_URL.'medida/edit' ?>" method="POST">
                              <button type="submit" class="btn btn-circle btn-secondary" data-bs-toggle="tooltip" data-bs-placement="right" title="Editar Medida">
                                 <i class="fas fa-marker"></i>
                              </button>
                              <input type="hidden" name="id" value="<?= $row['ID_medida'] ?>">
                           </form>

                           <a onclick="eliminarMed(<?= $row['ID_medida'] ?>)" href="#" data-bs-toggle="tooltip" data-bs-placement="right" title="Eliminar Medida" class="btn btn-circle btn-danger">
                              <i class="far fa-trash-alt"></i>
                           </a>
                        </td>
                     </tr>
                     <?php
                     }
                     ?>
               </tbody>
            </table>
         </div>
   </div><!-- fin de row -->
</div><!-- Fin container -->
<?php
}else{
?>
   <div class="alert alert-color alert-dismissible fade show" role="alert">
      <?= $this->datos['response_msg']  ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
         <span aria-hidden="true">&times;</span>
      </button>
   </div>
<?php
}
?>