<!-- col 12 -->
<br><br><br><br><br>
<div class="col-md-12 ">
<div class="col-lg-4 col-md-6 col-12 col-sm-6 shadow-lg mx-auto text-center my-4  alert alert-danger alert-dismissible fade show" role="alert">
               <h1 class="alert-100" >No ha iniciado sesion</h1> 
               <p>Está ingresando de manera incorrecta al sistema</p><br>
            </div>


      <div class="col-md-3"></div>
   </div>


</div><br><br><br><br>