
    <br>
    <div class="container relative my-4">
        <div class="container relative">
            <div class="section-text mb-60 mb-sm-40">
                <div class="row mb-60 my-2">
                    <div class="col-sm-6 mx-auto wow animate__animated animate__slideInLeft" style="visibility: visible; animation-name: fadeInLeft;">
                        <p>
                        <div class="container">
                            <h1>Contacto</h1>
                            <div class="contact-info">
                                <h2>Información</h2>

                                <p ><b>Dirección:</b> C/ Germán Bianor - 07100 Sóller (Mallorca)</p>
                                <p><b>Teléfono:</b> 663094553 - 647321451</p>
                                <p><b>Correo electrónico:</b> info@solucionesintegralesmallorca.com</p>
                                <div class="col-11">
                                    <img 
                                    onclick="PopupCenter('https://www.tiktok.com/@soluciones.int?_t=8dtveL7kNuw&_r=1', 'politicas', '1000', '1000');"
                                    class="btn-jav btn-chat-w  wow animate__animated animate__tada" 
                                    src="<?= RUTAS_APP['ruta_img'] . 'entity/tkt.png' ?>" 
                                    alt="Tiktok" 
                                    title="Click Tiktok"
                                    >
                                    <img 
                                    onclick="PopupCenter('https://www.facebook.com/profile.php?id=100094277083425', 'politicas', '1000', '1000');"
                                    class="btn-jav btn-chat-w  wow animate__animated animate__tada" 
                                    src="<?= RUTAS_APP['ruta_img'] . 'entity/facebook.png' ?>" 
                                    alt="Facebook" 
                                    title="Click Facebook"
                                    >
                                    
                                    <img 
                                    class="btn-jav btn-chat-w  wow animate__animated animate__tada" 
                                    src="<?= RUTAS_APP['ruta_img'] . 'entity/youtube.png' ?>" 
                                    alt="Youtube" 
                                    title="Click Youtube"
                                    >
                                    
                                    <img 
                                    onclick="PopupCenter('https://instagram.com/solucionesintegralesmallorca?igshid=MzNlNGNkZWQ4Mg==', 'politicas', '1000', '1000');"
                                    class="btn-jav btn-chat-w  wow animate__animated animate__tada" 
                                    src="<?= RUTAS_APP['ruta_img'] . 'entity/instagram.png' ?>" 
                                    alt="Instagram" 
                                    title="Click Instagram"
                                    >
                                </div>
                            </div>
                        </div>

                        </p>
                    </div>
                    <!-- 
                    <div class="col-sm-6 mb-sm-50 mb-xs-30 wow animate__animated animate__fadeInRight" style="visibility: visible; animation-name: fadeInRight;">
                        <img class=" img-entity img-fluid" src="<?= RUTAS_APP['ruta_img'] . 'entity/.png' ?>" width="500" height="338">
                    </div>
                     -->
                </div>

            </div>
        </div>
    </div>

</body>

<style>
    .btn-chat-w {
        width: 55px;
        height: 1%;
    }

    .contact-info {
        max-width: 500px;
        margin: 0 auto;
        color: #2f58a9
    }
    

    h1 {
        color: #2f58a9
    }

    .contact-info h2 {
        margin-bottom: 20px;
    }

    .contact-info p {
        margin-bottom: 10px;
    }

    body {
        font-family: "Roboto", arial, sans-serif;
    }

    .img-entity {
        border-radius: 3rem;
        border: 3.5px solid var(--naranja-sicloud);
        z-index: 1;
    }
</style>