version: '3.6'

services:
  portafolio_app:
    env_file:
      - .env
    container_name: portafolio_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laraveluser
        uid: 1000
    ports:
      - "8003:80"
    volumes:
      - .:/var/www/html
      - .:/var/www/html/session 


    networks:
      - my_network

networks:
  my_network:
      external: true
      name: my_network