<div class="my-4">
    <?php

    ?>
</div>
<?php
if (isset($_SESSION['message'])) {
?>
    <!-- alerta boostrap -->
    <div class=" col-md-4 text-center mx-auto alert alert-<?php echo $_SESSION['color']   ?> alert-dismissible fade show" role="alert">
        <?php echo  $_SESSION['message']  ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>


<?php setMessage();
}
cardtitulo("Modulo Comercial");
cardAviso();
?>


<div class="col-md-10 my-4 mx-auto">
    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-10 mx-auto">
            <div id="carousel-1" class="carousel slide  " data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-1" data-slide-to="1"></li>
                    <li data-target="#carousel-1" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="<?= RUTAS_APP['ruta_img'] ?>slideprod0.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="<?= RUTAS_APP['ruta_img'] ?>slideprod1.jpg" alt="Second slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>
<hr class="border ">

<div class="col-md-10 mt-5 my-4 mx-auto">
    <div class="row">
        <div class="col-md-10 box-card card card-body mx-auto shadow p-3 mb-5 bg-white rounded ">

            <div class="container-fluid">
                <div class="row">


                    <div class="card col-md-4 mx-auto card-body shadow p-3 mb-5 bg-white rounded text-center lead">
                        <h5 class="my-4"><span><i class="fas fa-shopping-cart"></i></span> PRODUCTOS</h5>
                        <div class="row mx-3">
                            <a class="btn btn-primary btn-block text-decoration-none " href="<?= BASE_URL . 'cliente/catalogo' ?>">Catálogo de productos</a>
                        </div>
                    </div>

                    <div class="card col-md-4 mx-auto  card-body shadow p-3 mb-5 bg-white rounded text-center lead">
                        <h5 class="my-4"><i class="fas fa-users"></i> USUARIOS</h5>
                        <div class="row mx-3">
                            <a class="btn btn-primary btn-block text-decoration-none " href="<?= BASE_URL . 'admin/controlUsuarios' ?>">Clientes y usuario</a>
                            <a class="btn btn-primary btn-block text-decoration-none " href="<?= BASE_URL . 'comercial/puntos' ?>">Acomulación de Puntos</a>
                            <a class="btn btn-primary btn-block text-decoration-none " href="<?= BASE_URL . 'factura' ?>">Facturación</a>
                        </div>
                    </div>

                    <div class="card  col-md-4 mx-auto card-body shadow p-3 mb-5 bg-white rounded text-center lead">
                        <h5 class="my-4"><span><i class="fas fa-file-medical-alt"></i></span> INFORMES</h5>
                        <div class="row mx-3">
                            <a class="btn btn-primary btn-block text-decoration-none " href="<?= BASE_URL . 'supervisor/facturas' ?>">Informes de Venta</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>