<?php
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
?>
<!doctype html>
<!--
	Fox by FreeHTML5.co
	Twitter: https://twitter.com/fh5co
	Facebook: https://fb.com/fh5co
	URL: https://freehtml5.co
-->
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Sporthealth</title>

  <!-- Bootstrap CSS -->
  <link href="css/animate.css" rel="stylesheet">
  <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="css/style.css">
</head>

<body>
<div class="container-fluid pl-0 pr-0 bg-img clearfix parallax-window2" data-parallax="scroll" data-image-src="<?= RUTAS_APP['ruta_img'] ?>images/banner2.jpg">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
      <div class="container">
        <!-- Brand -->
        <a class="navbar-brand mr-auto" href="#"><img src="<?= RUTAS_APP['ruta_img'] ?>images/logo.png" alt="FoxPro" /></a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar"> <span class="navbar-toggler-icon"></span> </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"> <a class="nav-link" href="index.html">Inicio</a> </li>
            <li class="nav-item"> <a class="nav-link" href="#about-us">Metodologia</a> </li>
            <li class="nav-item"> <a class="nav-link" href="#">Rutinas</a> </li>
            <li class="nav-item"> <a class="nav-link" href="#contact">Contacto</a> </li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container">
      <div class="fh5co-banner-text-box col-md-6">
        <div class="quote-box pl-5 pr-5 wow bounceInRight">
          <h2> FORMULARIO<br><span>LLENA TUS DATOS</span> </h2>
        </div>

        <a href="#formulario" class="btn text-uppercase btn-outline-danger btn-lg mr-3 mb-3 wow bounceInUp">Llenar formulario</a> <a href="index.html" class="btn text-uppercase btn-outline-danger btn-lg mb-3 wow bounceInDown"> Volver al inicio</a>
      </div>

    </div>

  </div>



  <footer class="container-fluid" id="formulario">
    <div class="container">
      <div class="row">
        <div class="col-md-3 footer1 d-flex wow bounceInLeft" data-wow-delay=".25s">
          <div class="d-flex flex-wrap align-content-center"> <a href="#"><img src="<?= RUTAS_APP['ruta_img'] ?>images/logo.png" alt="logo" /></a>
            <p>Lo mejor del mercado en nutricion y cuidado del cuerpo, Sporthealth</p>
            <p>&copy; 2021 Sporthealth. All rights reserved.<br> Design by <a href="http://portafoliojav.herokuapp.com/" target="_blank">SICLOUD</a>.</p>
          </div>
        </div>
        <div class="col-md-6 footer2 wow bounceInUp" data-wow-delay=".25s" id="contact">
          <a href="javascript:;" onclick="mostrar_div('form1'); mostrar_div('form2')">Si es tu primera cita ? cilck aqui</a>
          <div class="form-box" id='form1'>
            <h4>FORMULARIO</h4>
            <p class="text-dark">Si no se encutra registrado llene el formulario</p>
            <table class="table table-responsive d-table">
              <form  method="post">
              <input type="hidden" name="a" value="registro">
                <tr>
                  <td><input type="text" class="form-control pl-0" name="firt_name" placeholder="Primer Nombre" required /></td>
                  <td><input type="text" class="form-control pl-0" name="second_name" placeholder="Segundo Nombre" required/></td>
                </tr>
                <tr>
                  <td colspan="2"></td>
                </tr>
                <tr>
                  <td colspan="2"><input type="date" class="form-control pl-0" name="date_of_birth" placeholder="Fecha nacimiento" required/></td>
                </tr>
                <td colspan="2"><input type="text" class="form-control pl-0" name="last_name" placeholder="Apellidos" required/></td>
                </tr>
                <tr>
                  <td colspan="2"></td>
                </tr>
                <tr>
                  <td colspan="2"><input type="text" class="form-control pl-0" name="email" placeholder="Correo" required/></td>
                </tr>
                <tr>
                  <td colspan="2"></td>
                </tr>
                <td colspan="2">
                </td>
                <tr>
                  <td colspan="2"><input type="text" name="id_us" class="form-control pl-0" placeholder="Documento" required /></td>
                </tr>
                <tr>
                  <td colspan="2"></td>
                </tr>
                <tr>
                </tr>
                <tr>
                  <td colspan="2">
                    <label for="" class="text-dark">Documento</label>
                    <select name="fk_doc" id="" class="form-control" required>
                      <?php
                      foreach ($this->doc as $k => $d) {
                        echo '  <option ' . (isset($_POST['fk_doc']) && ($k == $_POST['fk_doc']) ? ' selected ' : '') . ' value="' . $k . '">' . $d . '</option>';
                      }
                      ?>
                    </select>
                  </td>
                </tr>
                <tr>
                  <td colspan="2">
                    <label for="" class="text-dark">Genero</label>
                    <select name="gender" id="" class="form-control" required>
                      <?php
                      foreach (['M' => 'Masculino', 'F' => 'Femenino'] as $k => $d) {
                        echo '  <option ' . ( isset($_POST['fk_doc']) && ($k == $_POST['fk_doc']) ? ' selected ' : '') . ' value="' . $k . '">' . $d . '</option>';
                      }
                      ?>
                    </select>
                  </td>
                </tr>
                <tr>
                <tr>
                  <td colspan="2" class="text-center pl-0"><button type="submit" class="btn btn-dark">ENVIAR DATOS</button></td>
                </tr>
              </form>
            </table>
          </div>
          
          <div id="form2" style="display: none;">
            <div class="form-box" >
              <h4>Solicitar cita</h4>
              <p class="text-dark">Digite numero de documento</p>
              <table class="table table-responsive d-table">
                <form method="post">
                <input type="hidden" name="a" value="solicitud">
                  <tr>
                    <td colspan="2"><input type="text" name="id_us" value="<?=($this->user[0]??'') ?>" class="form-control pl-0" placeholder="Documento" required/> </td>
                  </tr>
                  <tr>
                    <td colspan="2" class="text-center pl-0"><button type="submit" class="btn btn-dark">Solicitar cita</button></td>
                  </tr>
                </form>
              </table>
            </div>
            <div class="form-box" >
              <h4>Ver citas y estadistica</h4>
              <p class="text-dark">Digite numero de documento</p>
              <table class="table table-responsive d-table">
                <form action="<?= BASE_URL.'nutricion/asignar'?>" method="post">
                <input type="hidden" name="informe" >
                  <tr>
                    <td colspan="2"><input type="text" name="id_us" value="<?=($this->user[0]??'') ?>" class="form-control pl-0" placeholder="Documento" required /></td>
                  </tr>
                  <tr>
                    <td colspan="2" class="text-center pl-0"><button type="submit" class="btn btn-dark">Consultar</button></td>
                  </tr>
                </form>
              </table>
            </div>
            
          </div>
        </div>




        <div class="col-md-3 footer3 wow bounceInRight" data-wow-delay=".25s">
          <h5>DIRECCION</h5>
          <p>Calle 100 #12-23</p>
          <h5>TELEFONO</h5>
          <p>422-3454</p>
          <h5>CORREO</h5>
          <p>email@sporthealt.com</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Bootstrap JS, ... -->

  <script src="<?= RUTAS_APP['ruta_js'] ?>jquery.min.js"></script>

  <script>
    function mostrar_div(id, clase) {
      var main = ("#" + id);
      if (clase > 0) main = ("." + id)
      $(main).toggle('normal');
    }
  </script>

  <script src="<?= RUTAS_APP['ruta_js'] ?>bootstrap.min.js"></script>
  <script src="<?= RUTAS_APP['ruta_js'] ?>parallax.js"></script>
  <script src="<?= RUTAS_APP['ruta_js'] ?>wow.js"></script>
  <script src="<?= RUTAS_APP['ruta_js'] ?>main.js"></script>



</body>

</html>