<body>
<?php

?>

<div class="container-fluid pl-0 pr-0 bg-img clearfix parallax-window2" data-parallax="scroll" data-image-src="<?=RUTAS_APP['ruta_img'] ?>images/banner2.jpg">

  
  <div class="container" style="color: #fff !important; ">
    <div class="fh5co-banner-text-box col-md-6">
      <div class="quote-box pl-5 pr-5 wow bounceInRight">
        <h2> MARCA <br><span>LIDER EN NUTRICION</span> </h2>
      </div>
      
      <a href="<?= BASE_URL.'index/login' ?>" class="btn text-uppercase btn-outline-danger btn-lg mr-3 mb-3 wow bounceInUp">Iniciar Sesion</a> <a href="<?= BASE_URL.'index/formulario' ?>" class="btn text-uppercase btn-outline-danger btn-lg mb-3 wow bounceInDown"> Ir a formulario</a> </div>
      
  </div>
  
</div>
<div class="container-fluid fh5co-network">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4 class="wow bounceInUp" id="network">PARA NUESTRO</h4>
        <h2 class="wow bounceInRight">EQUIPO</h2>
        <hr />
        <h5 class="wow bounceInLeft">Sporthealth</h5>
        <p class="wow bounceInDown">La nutrición es la ingesta de alimentos en relación con las necesidades dietéticas del organismo. Una buena nutrición (una dieta suficiente y equilibrada combinada con el ejercicio físico regular) es un elemento fundamental de la buena salud.</p>
      </div>
      <div class="col-md-6">
        <figure class="wow bounceInDown"> <img src="<?= RUTAS_APP['ruta_img']?>images/about-img2.jpg" alt="gym" class="img-fluid" /> </figure>
      </div>
    </div>
  </div>
</div>
<div id="about-us" class="container-fluid fh5co-about-us pl-0 pr-0 parallax-window" data-parallax="scroll" data-image-src="images/about-us-bg.jpg">
  <div class="container">
    <div class="col-sm-6 offset-sm-6">
      <h2 class="wow bounceInLeft" data-wow-delay=".25s">¿PORQUE ELEGIR SPORTHEALTH?</h2>
      <hr/>
      <p class="wow bounceInRight" data-wow-delay=".25s">Hemos conseguido que Sporthealth sea sinónimo de suplementos deportivos de calidad. Todos ellos fabricados en nuestras instalaciones. Allí, nuestro equipo técnico trabaja día a día para ofrecerte lo mejor en nutricion.</p>
       </div>
  </div>
</div>
<div class="container-fluid fh5co-content-box">
  <div class="container">
    <div class="row">
      <div class="col-md-5 pr-0"><img src="<?= RUTAS_APP['ruta_img']?>images/rode-gym.jpg" alt="gym" class="img-fluid wow bounceInLeft" /> </div>
      <div class="col-md-7 pl-0">
        <div class="wow bounceInRight" data-wow-delay=".25s">
          <div class="card-img-overlay">
            <p>Puedes practicar deporte, puedes ser joven, pero si no te alimentas correctamente tu cuerpo sufrirá tarde o temprano
              - <i>Juan Armando Corbin</i>
            </p>
          </div>
          <img src="<?= RUTAS_APP['ruta_img']?>images/gym-girls.jpg" alt="girls in gym" class="img-fluid" /> </div>
      </div>
    </div>

 
  </div>
</div>
<footer class="container-fluid mb-0">
  <div class="container">
    <div class="row">
      <div class="col-md-8 footer1 d-flex wow bounceInLeft" data-wow-delay=".25s">
        <div class="d-flex flex-wrap align-content-center"> <a href="#"><img src="<?= RUTAS_APP['ruta_img']?>images/logo.png" alt="logo" class="mt-3" /></a>
        <a href="#"><img src="<?= RUTAS_APP['ruta_img']?>images/Sicloud.png" alt="logo" class="w-25 mt-3 ml-3"/></a>
          <p>&copy; 2021 Sporthealth. All rights reserved.<br> Design by <a href="https://sistem-sicloud.herokuapp.com" target="_blank">SICLOUD</a>.</p>
        </div>
      </div>

      <div class="col-md-3 footer3 wow bounceInRight" data-wow-delay=".25s">
        <h5>DIRECCION</h5>
        <p>Calle 100 #12-34</p>
        <h5>TELEFONO</h5>
        <p>412-3454</p>
        <h5>CORREO</h5>
        <p>soporte@sporthealth.cc</p>
        <div class="social-links">
          <ul class="nav nav-item">
            <li><a href="https://www.facebook.com/fh5co" class="btn btn-secondary mr-1 mb-2"><img src="<?= RUTAS_APP['ruta_img']?>images/facebook.png" alt="facebook" /></a></li>
            <li><a href="#"  class="btn btn-secondary mr-1 ml-1 mb-2"><img src="<?= RUTAS_APP['ruta_img']?>images/whatsapp.png" style="width: 25px; height: 25px;" alt="Whatsapp" /></a></li>
            
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Optional JavaScript --> 
<!-- jQuery first, then Bootstrap JS, ... -->


<script src="<?= RUTAS_APP['ruta_js']?>bootstrap.min.js"></script>
<script src="<?= RUTAS_APP['ruta_js']?>parallax.js"></script>
<script src="<?= RUTAS_APP['ruta_js']?>wow.js"></script>
<script src="<?= RUTAS_APP['ruta_js']?>main.js"></script>



</body>
</html>