<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 mx-auto">




            <div class="card card-body border my-2 card-box">
                <div class="card card-body border my-3 shadow p-3 mb-5 bg-white ">

                    <hr class="border ">
                    <div class="col-md-10 my-4 mx-auto">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-10 mx-auto">
                                <div id="carousel-1" class="carousel slide  " data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
                                        <li data-target="#carousel-1" data-slide-to="1"></li>
                                        <li data-target="#carousel-1" data-slide-to="2"></li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <div class="carousel-item active">
                                            <img class="d-block w-100" src="<?= RUTAS_APP['ruta_img'] ?>prov1.png" alt="First slide">
                                        </div>
                                        <div class="carousel-item">
                                            <img class="d-block w-100" src="<?= RUTAS_APP['ruta_img'] ?>prov2.jpg" alt="tree slide">
                                        </div>
                                        <div class="carousel-item">
                                            <img class="d-block w-100" src="<?= RUTAS_APP['ruta_img'] ?>prov3.png" alt="Second slide">
                                        </div>
                                    </div>
                                    <a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="border ">
<?php
if (isset($_SESSION['message'])) {
?>
                        <!-- alerta boostrap -->
                        <div class=" col-md-4 text-center mx-auto alert alert-<?php echo $_SESSION['color']   ?> alert-dismissible fade show" role="alert">
                            <?php echo  $_SESSION['message']  ?>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

<?php
}
setMessage() 
?>
                    <div class="card card-body   bg-white  col-md-10 my-2 mx-auto m-2 shadow border-abajo">
                        <h4 class="mx-auto">Informes</h4><!-- incio de card consultas -->
                        <div class="col-md-12 my-2">
                            <!-- sesion de prodcutos -->
                            <div class="row  mx-auto">
                                <div class="col-md-4 mx-auto ">
                                    <a class="btn btn-primary  btn-block" href="<?= BASE_URL.'logistica/categoria' ?>"> <i class="fas fa-fw fa-folder"></i>Productos por categoría</a>
                                </div><!-- fin de col de 4 1 -->
                                <div class="col-md-4 mx-auto">
                                    <a class="btn btn-primary  btn-block" href="<?= BASE_URL.'logistica/cantidad' ?>"> <i class="fas fa-fw fa-chart-area"></i>Cantidad de productos</a>
                                </div><!-- fin de col de 4 2 -->
                            </div><!-- fin de row -->
                        </div><!-- fin de col-md-12 -->
                    </div><!-- fin de card consulatas -->
                    <!-- inicio de sesion productos ------------------------------------------------------  -->
                    <div class="card card-body  shadow p-3 mb-5 bg-white mx-auto col-md-10 box-card ">
                        <h4 class="mx-auto">Procesos</h4><!-- inicio de card productos -->
                        <div class="col-md-12 my-2">
                            <!-- sesion de prodcutos -->
                            <div class="row">
                                <div class="col-md-4 ">
                                    <a class="btn btn-primary mx-auto btn-block" href="<?= BASE_URL.'producto/create'?>"> <i class="fas fa-fw fa-wrench"></i>Crear producto</a>
                                </div><!-- fin de col de 4 1 -->
                                <div class="col-md-4 ">
                                    <a class="btn btn-info mx-auto btn-block" href="<?= BASE_URL.'producto/ingreso'?>"><i class="fas fa-check"></i>Ingreso de producto pedido</a>
                                    <a class="btn btn-primary mx-auto btn-block" href="<?= BASE_URL.'producto?edit=1'?>"> <i class="fas fa-fw fa-wrench"></i>Editar productos</a>

                                </div><!-- fin de col de 4 2 -->
                                <div class="col-md-4 ">
                                    <a class="btn btn-primary mx-auto btn-block" href="<?= BASE_URL.'logistica/solicitud'?>"><i class="fas fa-arrow-right"></i>Solicitar pedido</a>

                                </div><!-- fin de col de 4 3 -->
                            </div><!-- fin de row -->
                        </div><!-- fin de col-md-12 -->
                    </div><!-- fin de card producto -->
                    <!-- fin de sesion producos ------------------------------  -->
                </div><!-- fin de card 2 -->
            </div><!-- fin de card 1-->
        </div><!-- fin col md -->
    </div><!-- fin row -->
</div><!-- container fluid -->