<!-- nav -->
<script src="<?= RUTAS_APP['ruta_js'] ?>reloj01.js"></script>
<?php
   require_once APP_LIBS. 'modal-login.phtml';
//@session_start();
if(!isset($_SESSION['usuario'])){
 
}   
function menuIndex($js = 1, $login = 1){
?>
<nav id="menu" class="navbar navbar-toggleable-md navbar-inverse  fixed-top navbar-expand-lg navbar">
    <a class="navbar-brand mx-3"  href="#">
        <img src="<?= RUTAS_APP['ruta_img'] ?>logoportal.png" width="250" height="65" alt="Logo ferreteria">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-5">
            <li class="nav-item active">
<?php
  if(isset($_SESSION['usuario'])) echo '<a class="nav-link ml-5" href="index">INICIO<span class="sr-only">(current)</span></a>';
?>
            </li>
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle px-3 " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    FERRETERIA
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<?= BASE_URL.'index/entidad' ?>">QUIENES SOMOS</a>
                    <a class="dropdown-item" href="<?= BASE_URL.'index/mision' ?>">MISION Y VISION</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link px-3 " href="<?= BASE_URL.'cliente/catalogo' ?>">CATALOGO DE PRODUCTOS<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link px-3 " href="<?= BASE_URL.'index/promocion' ?>">PROMOCIONES<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link pl-3 pr-5" href="<?= BASE_URL.'index/informes' ?>">CONTACTO<span class="sr-only">(current)</span></a>
            </li>
           <li>
             <div id="reloj" class="ml-5 mt-2 text-white"></div> 
           </li>
       
           

        </ul>

        <div class="ml-5">

<?php
if( isset($login) && $login ==  1 ){
?>     

<a href="#"
             class="text-white lead" data-toggle="modal" data-target="#signin"  style="position: absolute; top: 0; right: 0; margin: 24px;"     
<?php

/*
if( isset($js))
switch ($js) {
    case 0:
        echo 'href= "'.BASE_URL.'index/login"';
    break;
    case 1:
        echo 'onclick="abre()"  href="#"';
    break;

    
}

*/
?>  
             
             
             
             
             
             >Sign In
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-circle text-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z" />
                    <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                    <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z" />
                </svg><br>





                </a>
<?php
}
?>
        </div>
    </div>
</nav>

<?php
if(isset($js) && $js == 1){
?>
    <script>
        function abre() {
            if (window.screen) {
                var aw = screen.availWidth;
                var ah = screen.availHeight;
            }
            var sicloudWin = window.open('', 'Cicloud_Base', 'toolbar=0,location=0,directories=0,status=0, menubar=0,scrollbars=1,resizable=1, menubar=0, left=0, top=0, width=' + aw + ', height=' + ah);
            if (!sicloudWin || sicloudWin.closed) {
                sicloudWin.location = 'login';
            } else {
                var url = sicloudWin.location.toString();
                if (url.indexOf("<?=  BASE_URL.'login' ?>") != -1) sicloudWin.focus();
                else sicloudWin.location = 'login';
            }
        }
    </script>
<?php
}
}
?>
<!-- nav -->