
<div class=" mx-auto col-md-5 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 card card-body shadon mx-auto border-left-primary shadow h-100 py-2 mb-5">
                <div class="card-header shadow">
                    <h4 class="text-center   my-2"><em class="">Cambió de contraseña</em></h4>
                </div>
                <form action="" method="POST">

                    <div class="row">
                        <div class=" shadow h-100 py-2 mb-4 card card-body">
                            <h5 class="text-center mx-auto">Contraseña anterior </h5>
                            <div class="form-group"><input class="form-control" type="password" name="passA" value="" required autofocus maxlength="20"></div>
                            <h5 class="text-center mx-auto">Nueva contraseña </h5>
                            <div class="form-group"><input class="form-control" type="password" name="passN" value="" required autofocus maxlength="20"></div>
                            <h5 class="text-center mx-auto">Repita contraseña </h5>
                            <div class="form-group"><input class="form-control" type="password" name="passN2" value="" required autofocus maxlength="20"></div>
                            <div class="form-group"><input class="form-control" type="password" name="token" placeholder="Token Sicloud" value="" required autofocus maxlength="20"></div>
                            <input type="hidden" name="accion" value="cambioContrasena">
                            <input type="submit" name="submit" class="btn btn-primary btn-block" value="cambiar">  
        
                            <?php

                    if (isset($_SESSION['message'])) {
?>
    <!-- alerta boostrap -->
    <div class="col-md-12 mx-auto my-2 alert alert-<?php echo $_SESSION['color']   ?> alert-dismissible fade show" role="alert">
        <?php
                        echo  $_SESSION['message']  ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php
                    }
?>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
<br>

<script>
function aviso(){
    alert('El método funciona correctamente, pero Javier desactivo actualización por motivos de seguridad, si es requerido habilitar favor comunicarse con el administrador');
}
</script>