<!-- col 12 -->


<br><br><br><br><br>
<div class="col-md-12 ">
<div class="col-lg-4 col-md-6 col-12 col-sm-6 shadow-lg mx-auto text-center my-4 card-body  fade show alert-danger alert-dismissible" role="alert">
               <h1 class="alert-100" >No tiene permiso para ingresar a este modulo</h1> 
               <p>Solicite a administrador</p><br>
            </div>


      <div class="col-md-3"></div>
   </div>


</div><br><br><br><br>