<br><br>
<div class="container">
   <div class="card text-center shadow">
      <div class="card-title whadow">

         <h3 class="my-4">POLÍTICA DE PRIVACIDAD Y TÉRMINOS DE USO
         </h3>
         <div class="card-body">

            <h6 class=" text-left">Política De Privacidad</h6><br>
            <p class="my-2 text-left">Por medio de nuestra política de privacidad le ponemos al tanto de las debidas condiciones de uso en este sitio. <br>
               La utilización de estos implica su aceptación plena y sin reservas a todas y cada una de las disposiciones incluidas en este Aviso Legal, por lo que, si usted no está de acuerdo con cualquiera de las condiciones aquí establecidas, no deberá usar u/o acceder a este sitio. <br>
               Reservamos el derecho a modificar esta Declaración de Privacidad en cualquier momento. <br>  Su uso continuo de cualquier porción de este sitio tras la notificación o anuncio de tales modificaciones constituirá su aceptación de tales cambios.
            </p><br><br><br>
            <h6 class=" my-2 text-left">Política De Protección De Datos Personales</h6><br>
            <p class="my-2 text-left">Para utilizar algunos de los servicios o acceder a determinados contenidos, deberá proporcionar previamente ciertos datos de carácter personal,
               que solo serán utilizados para el propósito que fueron recopilados: enviarle información del tema de su interés. <br>
               El tipo de posible información que le sea solicitada incluye, de manera enunciativa más no limitativa, su nombre y dirección de correo electrónico (e-mail), entre otros,
               no toda la Información solicitada al momento de participar en el sitio es obligatoria de proporcionarse, salvo aquella que consideremos conveniente y que así se le haga saber.
               Cómo principio general, este sitio no comparte ni revela información obtenida, excepto cuando haya sido autorizada por usted, o en los siguientes casos:
               a) Cuando le sea requerido por una autoridad competente y previo el cumplimiento del trámite legal correspondiente y b)
               Cuando a juicio de este sitio sea necesario para hacer cumplir las condiciones de uso y demás términos de esta página, o para salvaguardar la integridad de los demás usuarios o del sitio. <br>
               Deberá estar consciente de que, si usted voluntariamente revela información personal en línea en un área pública, esa información puede ser recogida y usada por otros. Nosotros no controlamos las acciones de nuestros visitantes y usuarios.
            </p>
            <br><br>
            <h6 class=" text-left">Galletas o Cookies</h6><br>
            <p class="my-2 text-left">Este sitio hace uso de cookies, el cual son pequeños ficheros de datos que se generan en su ordenador, 
            este envía información sin proporcionar referencias que permitan deducir datos personales de este. <br>
               Usted podrá configurar su navegador para que notifique y rechace la instalación de las cookies enviadas por este sitio, sin que ello perjudique la posibilidad de acceder a los contenidos. 
               <br> Sin embargo, no nos responsabilizamos
               de que la desactivación de los mismos impida el buen funcionamiento del sitio.
            </p>
            <br><br>
            <h6 class=" text-left">Marcas Web o Web Beacons</h6><br>
            <p class="my-2 text-left">Al igual que las cookies este sitio también puede contener web beacons, un archivo electrónico gráfico que permite contabilizar a los usuarios que acceden al sitio o acceden a determinadas cookies del mismo, de esta manera, podremos ofrecerle una experiencia aún más personalizada.<br>
            </p>
            <br><br>
            <h6 class=" text-left">Acciones De Terceros</h6><br>
            <p class="my-2 text-left">Así mismo, usted encontrará dentro de este sitio, páginas, promociones, micrositios, tiendas virtuales, encuestas, patrocinadores, publicistas, contratistas y/o socios y servicios comerciales, en conjunto con otros servicios compartidos, propios o cobrandeados con terceros (”Sitios Cobrandeados”) que le podrán solicitar Información, los cuales este sitio le podrá revelar información proporcionada por usted.<br> <br>
               La Información que se proporcione en estos Sitios Cobrandeados está sujeta a las políticas de privacidad o leyendas de responsabilidad de Información que se desplieguen en dichos Sitios y no estará sujeta a esta política de privacidad.<br> Por lo que recomendamos ampliamente a los Usuarios a revisar detalladamente las políticas de privacidad que se desplieguen en los Sitios Cobrandeados.<br>
               Política De Privacidad De Fuentes De Rastreo Utilizadas En Este Sitio:
            </p>
            <br><br>
            <h6 class=" text-left">Conducta Responsable</h6><br>
            <p class="my-2 text-left">Toda la información que facilite deberá ser veraz.<br> A estos efectos, usted garantiza la autenticidad de todos aquellos datos que comunique como consecuencia de la cumplimentación de los formularios necesarios para la suscripción de los Servicios, acceso a contenidos o áreas restringidas del sitio.<br> En todo caso usted será el único responsable de las manifestaciones falsas o inexactas que realice y de los perjuicios que cause a este sitio o a terceros por la información que facilite.<br>
Usted se compromete a actuar en forma responsable en este sitio y a tratar a otros visitantes con respeto.

            </p>







         </div>

      </div>
   </div>
   <br><br><br><br><br>
</div>