<?php
if (isset($_SESSION['usuario']) && $_SESSION['usuario']['fk_rol'] == 'D') $edita = true;
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
?>



<body style="background: rgb(0,0,0);
background: linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(61,59,55,1) 35%);">
   <?php
   if ($edita == true) {
   ?>

      <div class="  col-md-8 mx-auto my-2 text-center border-arriba">
         <div class="row col-md-8 mx-auto" style="margin-top: 15%;">

            <div class="card card-body col-md-6 shadow " >
               <h6>Usuario</h6>
               <div class="card card-body mx-auto col-10 my-2 shadow border">

                  <form action="" method="POST">
                     <div class="form-group"><input type="text" id="buscarT" class="form-control " placeholder="Identidad" name="id_us" onchange="submit(this)" value=""></div>
                     <input type="hidden" name="informe">
                  </form>

               </div><!-- fin de card -->
            </div><!-- fin de primera divicion -->
            <div class="card card-body col-md-6 shadow">
               <h6>Estado de cita</h6>
               <form action="" method="post">
                  <div class="card card-body mx-auto col-10 my-2 shadow border">
                     <!-- formulario de filtro por rol -->

                     <div class="form-group">
                        <select name="rol" class="form-control " onchange="submit(this)">
                           <option selected="" value=""> -- Seleccione -- </option>
                           <?php
                           foreach ($this->status as $i => $d) {
                              echo '<option '.( (isset($_POST['rol'])) &&  ($i == $_POST['rol'])? ' selected ':'').' value="' . $i . '">' . $d . '</option>';
                           }
                           ?>
                        </select>
                     </div>
                  </div>

               </form>
            </div>
         </div>
      </div>
   <?php
   }
   ?>


   <div class="container-fluid mb-5 col-md-10" style="margin-top: 10%;">
      <div class="row">
         <div class="bg-dark col-md-12 mb-3 p-3">
            <h5 for="" style="text-align: center;" class="text-white">PACIENTES
               <form action="<?= BASE_URL . 'nutricion/informe' ?>" method="post">
                  <input type="hidden" name="id_us" value="<?= ($_POST['id_us'] ??'' )?>">
<?php
if( isset($_POST['id_us'])) echo ' <button type="submit" class="btn btn-succes btn-sm">Ver estadistica</button>';
?>
               </form>
            </h5>
         </div>
         <?php
         if ($this->datos['response_status'] == 'ok') {
         ?>

            <div class="col-lg-12 col-md-12 card p-3">
               <div class="table-responsive">
                  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                     <thead>
                        <tr>
                           <th>Tipo</th>
                           <th>Documento</th>
                           <th>Nombre</th>
                           <th>Rol</th>
                           <th>Fecha de solicitud</th>
                           <th width="100">Fecha de cita</th>
                           <th>Observacion </th>
                           <th>Id cita</th>
                           <th  width="200" >Doctor</th>
                           <th  width="200">Estado</th>
                           <?php
                           if (isset($edita) && $edita) echo '<th>Acciones</th>';
                           ?>

                        </tr>
                     </thead>
                     <tbody>
                        <?php

                        $selDoctor =$sel = '';
                        foreach ($this->doctor as $i => $d) {
                           $selDoctor .= '<option ' . (( isset( $_POST['doctor'])  && $i == $_POST['doctor']) ? ' selected ' : '') . ' value="' . $i . '">' . $d . '</option>';
                        }

                        $e = ( isset($edita) && ($edita) ? $e = '' : ' disabled ');
                        foreach ($this->datos['response_msg'] as $d) {
                           $htmFecha = ($d[4] == '0000-00-00 00:00:00') ? '<input type="date" name="fecha_asig" ' . $e . ' class="form-control">
                           <input type="time" ' . $e . ' name="hora" class="form-control"> ' : $d[4];
                           $htmObs  = (($d[5] == '') ? '<textarea ' . $e . ' name="obs"  cols="20" rows="5" class="form-control"></textarea>' : $d[5]);
                           if ($d[6] == 'S') {
                              $htmDoct = '<select name="doctor"class="form-control" width="500">' . $selDoctor . '</select>';
                           } else {
                              $htmDoct = 'Asignado';
                           }
                        ?>
                           <tr>
                              <form action="" method="post">
                                 <input type="hidden" name="update">
                                 <input type="hidden" value="<?= $d[1] ?>" name="id_us">
                                 <input type="hidden" value="<?= $d[2] ?>" name="id_cita">
                                 <td><?= $d[0] ?></td>
                                 <td><?= $d[1] ?></td>
                                 <td><?= $d[7] ?></td>
                                 <td><?= ($d[8] ?? '') ?></td>
                                 <td><?= $d[3] ?></td>
                                 <td><?= $htmFecha ?></td>
                                 <td><?= $htmObs ?></td>
                                 <td><?= $d[2] ?></td>
                                 <td><?= $htmDoct ?></td>
                                 <td>
                                    <?php
                                    if (isset($edita) &&  $edita ) {
                                    ?>

                                       <select name="status" class="form-control" width="500">
                                          <?php
                                          foreach ($this->status as $i => $v) {
                                             echo '<option  ' . (($i == $d[6]) ? ' selected ' : '') . ' value="' . $i . '">' . $v . '</option>';
                                          }
                                          ?>
                                       </select>
                                    <?php
                                    } else {
                                       echo $this->status[$d[6]];
                                    }
                                    ?>


                                 </td>
                                 <?php
                                 if (isset($edita) &&  $edita ) {
                                 ?>

                                    <td>
                                       <button type="submit" class="btn btn-success">
                                          <i class="far fa-edit"></i>
                                       </button>
                              </form>
                              <form action="<?= BASE_URL . 'nutricion/paciente' ?>" method="post">
                                 <button type="submit" class="btn btn-danger" title="Anexar medidas de usuario ">
                                    A

                                 </button>
                                 <input type="hidden" value="<?= $d[1] ?>" name="id_us">
                              </form>
                              </td>

                           </tr>
                     <?php
                                 }
                              }
                     ?>


                     </tbody>
                  </table>
               </div>
            </div>
         <?php
         }
         ?>

      </div>
   </div>


   <!-- Optional JavaScript -->
   <!-- jQuery first, then Bootstrap JS, ... -->

   <script src="js/jquery.min.js"></script>
   <script src="js/bootstrap.min.js"></script>
   <script src="js/parallax.js"></script>
   <script src="js/wow.js"></script>
   <script src="js/main.js"></script>

   <script type="text/javascript" src="DataTables/JSZip-2.5.0/jszip.min.js"></script>
   <script type="text/javascript" src="DataTables/pdfmake-0.1.36/pdfmake.min.js"></script>
   <script type="text/javascript" src="DataTables/pdfmake-0.1.36/vfs_fonts.js"></script>
   <script type="text/javascript" src="DataTables/DataTables-1.10.24/js/jquery.dataTables.min.js"></script>
   <script type="text/javascript" src="DataTables/DataTables-1.10.24/js/dataTables.bootstrap4.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/dataTables.buttons.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/buttons.bootstrap4.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/buttons.html5.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/buttons.print.min.js"></script>

   <script src="main.js"></script>
</body>

</html>