<?php
if (isset($_SESSION['usuario']) && $_SESSION['usuario']['fk_rol'] == 'D') $edita = true;
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
?>

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<body style="background: rgb(0,0,0);
background: linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(61,59,55,1) 35%);">
   <?php
 //  if ($edita == true) {
   ?>
   <form action="" method="POST">
      <div class="  col-md-10 mx-auto my-2 text-center border-arriba">
         <div class="row col-md-8 mx-auto" style="margin-top: 15%;">

            <div class="card card-body col-md-6 shadow " >
               <h6>Usuario</h6>
               <div class="card card-body mx-auto col-10 my-2 shadow border">

               
                     <div class="form-group"><input type="text" id="buscarT" class="form-control " placeholder="Identidad" name="id_us" value=""></div>
                     <input type="hidden" name="informe">
                

               </div><!-- fin de card -->
            </div><!-- fin de primera divicion -->
            <div class="card card-body col-md-6 shadow">
               <h6>Periodo</h6>
           
                  <div class="card card-body mx-auto col-10 my-2 shadow border">
                     <!-- formulario de filtro por rol -->
               Fecha inicial
               <input type="date" name="fI" value="<?= $_POST['fI']??date('Y-m-d')  ?>" class="form-control">
               Fecha final
               <input type="date"name="fF" value="<?= $_POST['fF']??date('Y-m-d')  ?>" class="form-control">
                           </div>
               <input type="submit" value="consulta" class="form-control btn-primary">

             
            </div>
         </div>
      </div>
      </form>
   <?php
   //}
   ?>


   <div class="container-fluid mb-5 col-md-10" style="margin-top: 10%;">
      <div class="row">
         <div class="bg-dark col-md-12 mb-3 p-3">
            <h5 for="" style="text-align: center;" class="text-white ">PACIENTES
               <form action="<?= BASE_URL . 'nutricion/informe' ?>" method="post">
                  <input type="hidden" name="id_us" value="<?= ($_POST['id_us']??'') ?>">
                  <br>

<?php
if( isset($_POST['id_us'])  && !empty($_POST['id_us'])  ) echo ' <button type="submit" class="btn btn-success btn-sm">Ver estadistica</button>';
echo ' <a href="'.BASE_URL.'nutricion/creaPlan" class="btn btn-success btn-sm">Crear plan</a>';
?>

               </form>
            </h5>
         </div>
         <?php
         if ($this->datos['response_status'] == 'ok') {
         ?>

            <div class="col-lg-12 col-md-12 card p-3">
               <div class="table-responsive">
                  <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                     <thead>
                        <tr>
                           <th>Nombre de plan</th>
                           <th>Comida</th>
                           <th>Instrucciones</th>
                           <th>Porciones</th>
                           <th>Tipo doc</th>
                           <th>Documento</th>
                           <th>Cliente</th>
                           <th>Fecha de solicitud</th>
                           <?php
                           if ($isset($edita) && $edita) echo '<th>Acciones</th>';
                           ?>

                        </tr>
                     </thead>
                     <tbody>
                        <?php

                        $sel = '';
                        if( isset($this->doctor) && count($this->doctor)>0) foreach ($this->doctor as $i => $d) {
                           $selDoctor .= '<option ' . (($i == $_POST['doctor']) ? ' selected ' : '') . ' value="' . $i . '">' . $d . '</option>';
                        }

                        $e = ((isset($edita) && $edita) ? $e = '' : ' disabled ');
                        foreach ($this->datos['response_msg'] as $d) {
                        ?>
                           <tr>
                              
                              <form action="" method="post">
                                 <input type="hidden" name="idUs"  value="<?= ($d[6].'||'.$d[8]) ?>"  >
                                 <td><?= $d[1] ?></td>
                                 <td><?= $d[9] ?></td>
                                 <td><textarea class="forn-control" name="obs" id="" cols="30" rows="10"><?= $d[4] ?></textarea></td>
                                 <td><?= ($d[5]??'') ?></td>
                                 <td><?= $d[6] ?></td>
                                 <td><?= $d[8] ?></td>
                                 <td><?= $d[7] ?></td>
                                 <td><?= $d[2] ?></td>
                                 <?php
                                    if (isset($edita) && $edita && isset($this->status) ) {
                                    ?>
                                 <td>
                                 <select name="status" class="form-control" width="500">
                                    <?php
                                    foreach ($this->status as $i => $v) {
                                       echo '<option  ' . (($i == $d[6]) ? ' selected ' : '') . ' value="' . $i . '">' . $v . '</option>';
                                    }
                                    ?>
                                 </select>
                                 </td>
                                 <?php
                                    } else {
                                      if(isset($this->status[$d[6]])) echo $this->status[$d[6]];
                                    }
                                    ?>
                                 <?php
                                 if (isset($edita) && $edita) {
                                 ?>

                                    <td>
                                       <button type="submit" class="btn btn-success">
                                          <i class="far fa-edit"></i>
                                       </button>
                              </form>
                              <form action="<?= BASE_URL . 'nutricion/paciente' ?>" method="post">
                                 <button type="submit" class="btn btn-danger" title="Anexar medidas de usuario ">
                                    A

                                 </button>
                                 <input type="hidden" value="<?= $d[1] ?>" name="id_us">
                              </form>
                              </td>

                           </tr>
                     <?php
                                 }
                              }
                     ?>


                     </tbody>
                  </table>
               </div>
            </div>
         <?php
         }
         ?>

      </div>
   </div>


   <!-- Optional JavaScript -->
   <!-- jQuery first, then Bootstrap JS, ... -->

   <script src="js/jquery.min.js"></script>
   <script src="js/bootstrap.min.js"></script>
   <script src="js/parallax.js"></script>
   <script src="js/wow.js"></script>
   <script src="js/main.js"></script>

   <script type="text/javascript" src="DataTables/JSZip-2.5.0/jszip.min.js"></script>
   <script type="text/javascript" src="DataTables/pdfmake-0.1.36/pdfmake.min.js"></script>
   <script type="text/javascript" src="DataTables/pdfmake-0.1.36/vfs_fonts.js"></script>
   <script type="text/javascript" src="DataTables/DataTables-1.10.24/js/jquery.dataTables.min.js"></script>
   <script type="text/javascript" src="DataTables/DataTables-1.10.24/js/dataTables.bootstrap4.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/dataTables.buttons.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/buttons.bootstrap4.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/buttons.html5.min.js"></script>
   <script type="text/javascript" src="DataTables/Buttons-1.7.0/js/buttons.print.min.js"></script>

   <script src="main.js"></script>
</body>

</html>