<?php
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
?>

<!--
	Fox by FreeHTML5.co
	Twitter: https://twitter.com/fh5co
	Facebook: https://fb.com/fh5co
	URL: https://freehtml5.co
-->
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Sporthealth</title>

  <!-- Bootstrap CSS -->
  <link href="css/animate.css" rel="stylesheet">
  <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="css/style.css">
  <!-- Start of HubSpot Embed Code -->
  <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/19562886.js"></script>
<!-- End of HubSpot Embed Code -->
</head>
<body>
<div class="container-fluid pl-0 pr-0 bg-img clearfix parallax-window2" data-parallax="scroll" data-image-src="images/banner2.jpg">

  <div class="container">
    <div class="fh5co-banner-text-box col-md-6">
      <div class="quote-box pl-5 pr-5 wow bounceInRight">
        <h2> Bienvenido <br><span>ESPECIALISTA</span> </h2>
      </div>
      
 <a href="#panel" class="btn text-uppercase btn-outline-danger btn-lg mb-3 wow bounceInDown">VER PANEL ADMINSITRATIVO</a> </div>
      
  </div>
  
</div>
<div class="container-fluid fh5co-network" style="background: rgb(0,0,0);
background: linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(61,59,55,1) 35%);">
  <div class="container">
    <div class="row" id="panel">
    <div class="bg-dark col-md-12 mb-3 p-3" ><h5 for="" style="text-align: center;" class="text-white" >PANEL ADMINISTRATIVO</h5></div>
            <div class="card col-md-12" style="background-color: black; opacity: .7;">
                <div class="card-body">
                    <div class="card p-3">
                        <h5 style="text-align: center;">PACIENTES</h5>
                        <hr style="width: 1000px; margin: auto;" class="mb-5"/>
                        <a href="<?= BASE_URL.'nutricion/asignar' ?>" class="btn btn-dark my-2 mx-5" >Asignar citas</a>
                        <a href="<?= BASE_URL.'nutricion/asignaPlan' ?>" class="btn btn-dark mx-5">Agragar plan</button>
                        <a href="<?= BASE_URL.'nutricion/reportes' ?>" class="btn btn-dark mx-5 my-2 mx-5">Reportes</a>
                    </div>
                    <div class="card p-3 mt-3">
                        <h5 style="text-align: center;">MI CUENTA</h5>
                        <hr style="width: 1000px; margin: auto;" class="mb-5"/>
                        <a href="<?= BASE_URL.'nutricion/perfil' ?>" class="btn btn-dark mx-5">Mi perfil</a>
                        <a href="<?= BASE_URL.'index/cerrar' ?> " class="btn btn-danger  my-2  mx-5">Cerrar sesion</a>
                        
                    </div>
                </div>
            </div>
    </div>
  </div>
</div>


<!-- Optional JavaScript --> 
<!-- jQuery first, then Bootstrap JS, ... -->

<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/parallax.js"></script>
<script src="js/wow.js"></script>
<script src="js/main.js"></script>

<script src="js/widget.js"></script>
<script>
var mostrarValor = function(x){
document.getElementById('chat').value=x;
}

  
</script>

</body>
</html>