
<?php
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

?>

<body style="background: rgb(0,0,0);
background: linear-gradient(90deg, rgba(0,0,0,1) 0%, rgba(61,59,55,1) 35%);">



    <div class="container mb-5" style="margin-top: 10%;">
        <div class="row">
            <div class="bg-dark col-md-12 mb-3 p-3">
                <h5 for="" style="text-align: center;" class="text-white">PACIENTES</h5>
            </div>

<?php
$g= ['M'=>'Masculino', 'F'=>'Femenino'];
if($this->datos['response_status']=='ok'){
?>

            <div class="col-lg-12 card p-3">
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Tipo D</th>
                                <th>Usuario</th>
                                <th>genero</th>
                                <th>Fecha de registro</th>
                                <th>Registro</th>
                                <th>Nomenclatura</th>
                                <th>Medida</th>
                            </tr>
                        </thead>
                        <tbody>
<?php
foreach ($this->datos['response_msg'] as $d) {
?>
                            <tr>
                                <td><?= $d[0] ?></td>
                                <td><?= $d[1] ?></td>
                                <td><?= $g[$d[4]] ?></td>
                                <td><?= $d[3] ?></td>
                                <td><?= $d[6] ?></td>
                                <td><?= $d[7] ?></td>
                                <td><?= $d[8] ?></td>
                            </tr>
<?php
}
?>
                        </tbody>
                    </table>
                </div>
            </div>
<?php
}
?>
        </div>
    </div>
</body>
</html>