<!-- col 12 -->


<br><br><br><br><br>
<div class="col-md-12 ">
<div class="col-lg-4 col-md-6 col-12 col-sm-6 shadow-lg mx-auto text-center my-4 card-body  fade show alert-danger alert-dismissible" role="alert">
               <h1 class="alert-100" >404</h1> 
               <p>No encuntra la ruta que resulve</p>
               <a class="btn btn-outline-primary" href="<?=  BASE_URL. 'index/login'  ?>">Login</a>
            </div>
      <div class="col-md-3"></div>
   </div>


</div><br><br><br><br>