<?php

if ($this->factura['response_status'] == 'OK') {
    $aU = $this->factura['response_msg'][0];
    $aP = $this->factura['response_msg'][1];
} else {
    die('<div class="col-lg-6 col-12 col-sm-12 shadow-lg mx-auto text-center my-4  alert alert-danger alert-dismissible fade show" role="alert">
    <h1>' . $this->factura['response_msg'] . '</h1> <br> 
    <a class="btn btn-outline-primary"  href="'.BASE_URL.'supervisor/consFactura'.' ">Seleccione otra factura</a>
    </div>');
}

if (count($aU) != 0) {
    foreach ($aU as $row) {
$txt='

                <div class=" card mx-auto container-fluid my-4 col-lg-11">
                    <div class="row">
                        <div class="col-lg-6">
                            <img src="'. RUTAS_APP['ruta_img'].'capsulelogo.PNG" alt="" style="width: 430px; height: 165px;">
                        </div>
                        <div class="col-lg-6 mt-4">
                            <div class="card p-2">Factura <br>'. $row['ID_factura'] .'</div>
                            <div class="card p-3">Fecha:      '. $row['fecha']      .'</div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-10 card card-body">
                            <div class=" row form-group mx-2 my-4 ">
                                          '. $row['nom_doc'] . ":   " . $row['ID_us'].'                         <br>
                                CLIENTE    :   '. $row['nom1'] .'  '. $row['nom2'] .'   '. $row['ape1'].'      <br>
                                E-MAIL     :   '. $row['correo'].'                                            <br>
                                DIRECCION  :   '. $row['dir'].'                                              <br>
                            </div>
                        </div>
                        <div class="col-lg-2 text-center">
                            <div class="row">
                                <div class="col-lg-12 card card-body">ORDEN DE COMPRA <br>N-A</div>
                                <div class="col-lg-12 card card-body">MEDIO DE PAGO <br>' . $row['nom_tipo_pago'].        '</div>
                                <div class="col-lg-12 card card-body">TIPO <br>     '. $row[12].'                          </div>';
}
$txt.='

                            </div>
                        </div>
                        <div class="col-lg-12 card card-body">
                            <table class=" table table-bordered table-striped bg-white table-sm shadow">
                                <thead>
                                    <tr>
                                        <td class="col-3">DESCRIPCIÓN</td>
                                        <td>CANT.</td>
                                        <td>VR.UNIT</td>
                                        <td>IVA</td>
                                        <td>TOTAL</td>
                                    </tr>
                                </thead>
                                <tbody>    
                                    ';
                                    
if (isset($aP)) {
    foreach ($aP as $row) {
$txt.='
                                    
                                <tr>
                                    <td class="col-3">'. $row['nom_prod']    .'</td>
                                    <td>'. $row['cantidad']                  .'</td>
                                    <td>  $'. number_format(($row['val_prod']), 0, ',', '.') .'</td>
                                    <td>  $'. number_format(((0.19 * ($row['val_prod'] * $row['cantidad']))), 0, ',', '.') .'</td>
                                    <td>  $'. number_format((($t = $row['cantidad'] * $row['val_prod'])), 0, ',', '.').'</td>
                                </tr>';
} // verfactural
$txt.='
                                </tbody>
                            </table>
                        </div>
                        <table class="table table-bordered table-striped ">
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-8 card">
                            <h5>VALOR EN LETRAS</h5>';

$v = new c_numerosLetras;
$totalpagar = $t;
$letra = ($v->convertirEurosEnLetras($aU[0][11]));
$txt.='
<div>
                                <span>'. ucfirst($letra).'</span>
                            </div>
                        </div>
                        <div class="col-lg-4 card card-body">
                            <h4>$'. number_format($aU[0][11], 0, ',', '.') .' </h3>
                        </div>
                    </div>
                </div>';
?>


<a href="javascript:window.print(); void 0;" style="color:#006666">Imprimir o Generar PDF</a>

<?php              
}   
echo $txt;    
$_SESSION['doc']= $txt;
echo '


'


;




//require_once(ROOT . 'libs/mpdf/repo.php');


if( isset($_POST['accion']) ){
   
switch ($_POST['accion']) {
    case 'expPDT':
        $_SESSION['doc']= $txt;
        //require_once(ROOT . 'libs/mpdf/repo.php');

        // $mpdf->Output();
        # code...
        break;
    
    default:
        # code...
        break;
}



}

} else {  ?>




<form action="'. BASE_URL .'/libs/mpdf/repo.php?exp=1" method="post"></form>

            <div class="row">
                <div class="col-lg-2 mx-auto my-4">
                    <div class="card card-body text-center">
                        <?= "No hay registros ";  ?>
                    </div>
                </div>
            </div>

<?php
}
?>
<script>

</script>


<?php
die();
